Difficulties = {
    "eas": "easy",
    "med": "medium",
    "har": "hard",
    "dif": "difficult",
    "cha": "challenging",
    "int": "intense",
    "rem": "remorseless",
    "ins": "insane",
    "ext": "extreme",
    "ter": "terrifying",
    "cat": "catastrophic",
}
Realms = {
    "r1": ("Ring 1", "ring"),
    "r2": ("Ring 2", "ring"),
    "r3": ("Ring 3", "ring"),
    "r4": ("Ring 4", "ring"),
    "r5": ("Ring 5", "ring"),
    "r6": ("Ring 6", "ring2"),
    "r7": ("Ring 7", "ring2"),
    "r8": ("Ring 8", "ring2"),
    "r9": ("Ring 9", "ring2"),
    "z1": ("Zone 1", "zone"),
    "z2": ("Zone 2", "zone"),
    "z3": ("Zone 3", "zone"),
    "z4": ("Zone 4", "zone"),
    "z5": ("Zone 5", "zone2"),
    "z6": ("Zone 6", "zone2"),
    "z7": ("Zone 7", "zone3"),
    "z8": ("Zone 8", "zone3"),
    "z9": ("Zone 9", "zone3"),
    "z10":( "Zone 10", "zone3"),
    "fr": ("Forgotten Ridge", "ring"),
    "ge": ("Garden of Eeshöl", "ring"),
    "goe":( "Garden of Eeshöl", "ring"),
    "er": ("Event Realm", "ring"),
    "lr": ("Lost River", "ring"),
    "pa": ("Paradise Atoll", "summer"),
    "aa": ("Arcane Area", "zone"),
    "pm": ("Pit of Misery", "zone"),
    "pom": ("Pit of Misery", "zone"),
    "pt": ("Practice Time", "cat"),
    "eh": ("Eclipsed Headquarters", "halloween"),
    "lm": ("Legacy Mini-Event", "ring"),
}
Towers = {
    "toast": ("Tower of Annoyingly Simple Trials", "r1", "Low eas"),
    "toh": ("Tower of Hecc" "r1", "Mid har")
}